version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
python:
   install:
     - requirements: requirements_docs.txt
     - method: pip
       path: .
