version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
python:
   version: 3.7
   install:
     - requirements: requirements_docs.txt
     - method: pip
       path: .
